name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Enable corepack for pnpm usage
        shell: sh
        run: corepack enable pnpm

      - name: Install
        run: pnpm i --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: yarn build
